### PR TITLE
Update operation.md

### PR DESCRIPTION
**Pull request by yoid2000**
ok, try again. (But the old branch needs to be deleted...)

### CODE REVIEW

**Comment by cristianberneanu** [comment]
Paul, are you sure about the change in order of sections? In the GUI, the suppression threshold configuration section comes first.

**Review by cristianberneanu — APPROVED** [review]

**Comment by cristianberneanu** [comment]
> Paul, are you sure about the change in order of sections? In the GUI, the suppression threshold configuration section comes first.

Nevermind, my brain misfired, this is the correct order.

**Comment by pdobacz** [comment]
> Paul, are you sure about the change in order of sections? In the GUI, the suppression threshold configuration section comes first.

I remember that there was a back and forth here, but it indeed comes second, on `master` at least.

**Comment by cristianberneanu** [comment]
Sorry, `master` hasn't been updated yet with the fix for the GH actions. I will update this branch and merge it once that is done.

**Pull request merged**
